<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Smart Mirror')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?=
                $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?=
                $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('css/weather/weather-icons.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap-reboot.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?=
                $this->headScript()
                ->prependFile($this->basePath('js/moment/moment-with-locales.min.js'))
                ->prependFile($this->basePath('js/moment/moment.min.js'))
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>

        <script>
            moment.locale('nl');
            var datetime = null,
                    date = null;

            var update = function () {
                date = moment(new Date())
                datetime.html(date.format('dddd, D MMMM [<br/>] YYYY, HH:mm'));
            };

            $(document).ready(function () {
                datetime = $('#datetime')
                update();
                setInterval(update, 1000);
            });
        </script>
    </head>
    <body>
        <div class="container-fluid mh-100">
            <?= $this->content ?>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
