<div class="row header">
    <div class="col text-left">
        <div id="weatherInfo">
            <span class="sunsetrise"></span>
            <br/>
            <span class="temp-wind"></span>
            <span class="foreCast">
                    <table id="foreCastTable"></table>
            </span>
        </div>
    </div>
    <div class="col text-right">
        <span id="datetime">
            <span class="date"></span><br/>
            <span class="time"></span>
        </span>
    </div>
</div>
<div class="row middle">
    <div class="col"></div>
</div>
<div class="row footer">
    <div class="col text-center align-text-bottom">
        <div id="newsFeed">
            <div class="textSlider">
                <ul>
                    <?php
                    foreach ($newsData AS $newsItem) {
                        echo '<li>' . $newsItem['title'] . '</li>';
                    }
                    ?>
                </ul>
            </div>
        </div>
    </div>
</div>