
<div class="row header">
    <div class="col text-center">
        <div id="weatherInfo">
            <?php echo $weatherData->main->temp ?><i class="wi wi-celsius"></i>
        </div>
    </div>
    <div class="col text-center">
        <h1>Welkom</h1>
    </div>
    <div class="col text-center">
        <span id="datetime"></span>
    </div>
</div>
<div class="row middle">
    <div class="col"></div>
</div>
<div class="row footer">
    <div class="col">test</div>
</div>