
<div class="row header">
    <div class="col text-left">
        <div id="weatherInfo">
            <span class="sunsetrise">
                <i class="wi wi-sunrise"></i><?php echo $weatherData['sunRise'] ?>
                <i class="wi wi-sunset"></i><?php echo $weatherData['sunSet'] ?>
            </span>
            <br/>
            <span class="temp-wind">
                    <i class="wi <?php echo $weatherData['icon'] ?>"></i> <?php echo $weatherData['temp'] ?><i class="wi wi-celsius"></i>
                    <i class="wi wi-strong-wind"></i> <?php echo $weatherData['windSpeed'] ?>
            </span>
        </div>
    </div>
    <div class="col text-right">
        <span id="datetime"></span>
    </div>
</div>
<div class="row middle">
    <div class="col"></div>
</div>
<div class="row footer">
    <div class="col text-center">
        <div id="newsFeed">
            <div class="textSlider">
                <ul>
                    <?php
                    foreach ($newsData AS $newsItem) {
                        echo '<li>' . $newsItem['title'] . '</li>';
                    }
                    ?>
                </ul>
            </div>
        </div>
    </div>
</div>